name: Deploy Azure Infrastructure
inputs:
  azure-creds:
    description: 'Azure service principal credentials JSON'
    required: true
  resource-group:
    description: 'Resource group name'
    required: true
  location:
    description: 'Azure region'
    required: true
  acr-name:
    description: 'Azure Container Registry name'
    required: true
  static-web-app:
    description: 'Static Web App name'
    required: true
  container-name:
    description: 'Container Instance name'
    required: true
  postgres-name:
    description: 'PostgreSQL server name'
    required: true
  redis-name:
    description: 'Redis cache name'
    required: true
runs:
  using: composite
  steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure-creds }}
    - name: Deploy infrastructure
      shell: bash
      run: |
        bash ${{ github.action_path }}/deploy.sh \
          "${{ inputs.resource-group }}" \
          "${{ inputs.location }}" \
          "${{ inputs.acr-name }}" \
          "${{ inputs.static-web-app }}" \
          "${{ inputs.container-name }}" \
          "${{ inputs.postgres-name }}" \
          "${{ inputs.redis-name }}"
