# Generated by Django 5.2.2 on 2025-06-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_category_and_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="age_group",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
