# Generated by Codex on 2025-06-05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_age_group_product_ingredients_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[('stripe', 'Stripe'), ('razorpay', 'Razorpay'), ('phonepe', 'PhonePe'), ('paytm', 'Paytm'), ('cashfree', 'Cashfree')], max_length=50, unique=True)),
                ("api_key", models.CharField(blank=True, max_length=255, null=True)),
                ("api_secret", models.CharField(blank=True, max_length=255, null=True)),
                ("active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ShiprocketConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.CharField(max_length=255)),
                ("token", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="carts", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("product", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="favorited_by", to="catalog.product")),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="favorites", to=settings.AUTH_USER_MODEL)),
            ],
            options={"unique_together": {("user", "product")}},
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("cart", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="items", to="catalog.cart")),
                ("product", models.ForeignKey(on_delete=models.deletion.CASCADE, to="catalog.product")),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="payment_gateway",
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name="orders", to="catalog.paymentgateway"),
        ),
        migrations.AddField(
            model_name="order",
            name="shiprocket_shipment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name="orders", to=settings.AUTH_USER_MODEL),
        ),
    ]

